### ISSUE TITLE
peft==0.4.0.dev0版本

### ISSUE THREAD

**Issue by onetwo12cn** [EvilPsyCHo/train_custom_LLM#3]
peft==0.4.0.dev0
要怎么下载啊，pip下载时候报错，没有这个版本。添加了各个镜像源也不行

**Comment by onetwo12cn** [comment]
> peft==0.4.0.dev0 要怎么下载啊，pip下载时候报错，没有这个版本。添加了各个镜像源也不行

**Comment by EvilPsyCHo** [comment]
github peft 项目里面拉最新的分支到本地安装
