### ISSUE TITLE
ValueError: Can't find 'adapter_config.json' at './output/baichuan_lorasft/'

### ISSUE THREAD

**Issue by JCjing-chenjing** [EvilPsyCHo/train_custom_LLM#5]
ValueError: Can't find 'adapter_config.json' at './output/baichuan_lorasft/'

**Comment by EvilPsyCHo** [comment]
hi 你是在运行Notebook教程代码报错的吗? 那是因为我本地训练的lora模型,并存储在'./output/baichuan_lorasft/' , 你需要本地训练并把自己保存的路径放过去才可以哦.
