### ISSUE TITLE
ValueError: Target modules [] not found in the base model. Please check the  target modules and try again.

### ISSUE THREAD

**Issue by JCjing-chenjing** [EvilPsyCHo/train_custom_LLM#8]
train: 
/opt/conda/envs/py310/bin/python train.py   --model_name baichuan \
    --model_path /Data/cj/ML/baichuan-inc/baichuan-7B \
    --quantization float16 \
    --data_name belle_open_source_500k \
    --data_path ./data/Belle_open_source_0.5M.json \
    --train_size 20000 \
    --output_dir ./output/baichuan_lorasft \
    --seed 42 \
    --max_len 1024  \
    --lora_rank 8 \
    --num_train_epochs 1 \
    --learning_rate 3e-4 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 8 \
    --gradient_accumulation_steps 1 \
    --logging_steps 10 \
    --evaluation_strategy steps \
    --save_strategy steps \
    --eval_steps 100 \
    --save_steps 100 \
    --report_to tensorboard \
    --save_total_limit 3 \
    --load_best_model_at_end true \
    --optim adamw_torch 
    
error:
     /Data/cj/ML/train_custom_LLM-main/train.py:105 in <module>                   │
│                                                                              │
│   102 │   model.save_pretrained(training_args.output_dir)                    │
│   103                                                                        │
│   104 if __name__ == "__main__":                                             │
│ ❱ 105 │   main()                                                             │
│                                                                              │
│ /Data/cj/ML/train_custom_LLM-main/train.py:74 in main                        │
│                                                                              │
│    71 │   )                                                                  │
│    72 │                                                                      │
│    73 │   print(config)                                                      │
│ ❱  74 │   model = get_peft_model(model, config)                              │
│    75 │                                                                      │
│    76 │   ############# prepare data ###########                             │
│    77 │   data = eval(args.data_name)(args.data_path, tokenizer, args.max_le │
│                                    
ValueError: Target modules [] not found in the base model. Please check the target modules and try again.

**Comment by Calajv** [comment]
I encountered the same problem！How did you solve this problem？
